name: release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    uses: ./.github/workflows/build.yml
  release:
    needs:
      - build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: artifacts

      - name: create release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create --repo "${{github.repository}}" --generate-notes "${{github.ref_name}}" artifacts/*.uf2
